title: Gorgi Chat
description: A modern, fast and secure chatting application.
theme: just-the-docs

url: https://gorgichat.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
